language: php

matrix:
  include:
    - php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-dist --no-interaction"
    - php: 7.4
      env:
        - COMPOSER_FLAGS="--prefer-dist --no-interaction"

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS

script: vendor/bin/simple-phpunit
